### ISSUE TITLE
Tried pushing to Predix Cloud

### ISSUE THREAD

**Issue by mgit7** [predixdesignsystem/px-sample-app-react#2]
I tried using this app as an example so I can get a feel of how to build and push an app onto Predix Cloud using React. I followed the instructions to run `npm install` and `bower install`. Then I inserted my manifest file into the project folder and tried pushing this app to the cloud and I keep getting this error, but the build is still successful. 

`[4/4] Building fresh packages...
       Done in 16.53s.
    error react-scripts@1.0.17: The engine "node" is incompatible with this module. Expected version ">=6".
error Found incompatible module
       yarn.lock is outdated`

After its done building, it keeps trying to run this instance on the cloud but fails and times out. Below is the logs that were produced.

>  2018-04-02T16:02:40.49-0700 [API/1] OUT Updated app with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 ({"state"=>"STOPPED"})
   2018-04-02T16:02:43.03-0700 [DEA/92] OUT Got staging request for app with id 7455ebd8-c0b0-4768-b9d6-c7083ab6a740
   2018-04-02T16:02:45.84-0700 [API/6] OUT Updated app with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 ({"state"=>"STARTED"})
   2018-04-02T16:02:49.40-0700 [STG/92] OUT -----> Downloaded app package (63M)
   2018-04-02T16:02:51.06-0700 [STG/92] OUT -----> Downloaded app buildpack cache (49M)
   2018-04-02T16:02:53.76-0700 [STG/0] OUT     -------> Buildpack version 1.5.29
   2018-04-02T16:02:53.79-0700 [STG/0] ERR     parse error: Expected another key-value pair at line 21, column 3
   2018-04-02T16:02:53.79-0700 [STG/0] ERR  !     Unable to parse package.json
   2018-04-02T16:02:53.79-0700 [STG/0] OUT -----> Build failed
   2018-04-02T16:02:53.80-0700 [STG/0] OUT        We're sorry this build is failing! You find more info about the nodejs buildpack here:
   2018-04-02T16:02:53.80-0700 [STG/0] OUT        https://docs.cloudfoundry.org/buildpacks/node/index.html
   2018-04-02T16:02:53.80-0700 [STG/0] OUT        Some possible problems:
   2018-04-02T16:02:53.80-0700 [STG/0] OUT        - This project was built with yarn, which is new and under development. Some projects can still be built more reliably with npm
   2018-04-02T16:02:53.80-0700 [STG/0] OUT        http://docs.cloudfoundry.org/buildpacks/node/node-tips.html
   2018-04-02T16:02:53.80-0700 [STG/0] OUT Staging failed: Buildpack compilation step failed
   2018-04-02T16:02:53.94-0700 [API/6] ERR encountered error: App staging failed in the buildpack compile phase
   2018-04-02T16:03:25.68-0700 [API/7] OUT Updated app with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 ({"name"=>"mgsdsu-predix-nodejs-starter", "command"=>"PRIVATE DATA HIDDEN", "memory"=>128, "buildpack"=>"nodejs_buildpack", "environment_json"=>"PRIVATE DATA HIDDEN"})
   2018-04-02T16:07:48.15-0700 [DEA/230] OUT Removing crash for app with id 7455ebd8-c0b0-4768-b9d6-c7083ab6a740
   2018-04-02T16:07:48.15-0700 [DEA/230] OUT Stopping app instance (index 0) with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740
   2018-04-02T16:07:48.15-0700 [DEA/230] OUT Stopped app instance (index 0) with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740
   2018-04-02T16:07:55.81-0700 [DEA/190] OUT Got staging request for app with id 7455ebd8-c0b0-4768-b9d6-c7083ab6a740
   2018-04-02T16:08:00.26-0700 [API/8] OUT Updated app with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 ({"state"=>"STARTED"})
   2018-04-02T16:08:03.84-0700 [STG/190] OUT -----> Downloaded app package (63M)
   2018-04-02T16:08:05.43-0700 [STG/190] OUT -----> Downloaded app buildpack cache (49M)
   2018-04-02T16:08:08.18-0700 [STG/0] OUT     -------> Buildpack version 1.5.29
   2018-04-02T16:08:08.21-0700 [STG/0] OUT -----> Creating runtime environment
   2018-04-02T16:08:08.22-0700 [STG/0] OUT        NPM_CONFIG_LOGLEVEL=error
   2018-04-02T16:08:08.22-0700 [STG/0] OUT        NPM_CONFIG_PRODUCTION=true
   2018-04-02T16:08:08.22-0700 [STG/0] OUT        NODE_VERBOSE=false
   2018-04-02T16:08:08.22-0700 [STG/0] OUT        NODE_ENV=production
   2018-04-02T16:08:08.22-0700 [STG/0] OUT        NODE_MODULES_CACHE=true
   2018-04-02T16:08:08.22-0700 [STG/0] OUT -----> Installing binaries
   2018-04-02T16:08:08.23-0700 [STG/0] OUT        engines.node (package.json):  unspecified
   2018-04-02T16:08:08.23-0700 [STG/0] OUT        engines.npm (package.json):   unspecified (use default)
   2018-04-02T16:08:08.39-0700 [STG/0] OUT        Downloading and installing node 4.7.3...
   2018-04-02T16:08:08.58-0700 [STG/0] OUT        WARNING: node 4 will no longer be available in new buildpacks released after 2018-04-01
   2018-04-02T16:08:08.58-0700 [STG/0] OUT        Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/a650821a-7cdd-4c2e-a81f-3453412f30a3_484b714a19dde2c8020f535def648881bd3cc90cbba9779639687f892291b9ab/dependencies/https___buildpacks.cloudfoundry.org_dependencies_node_node-4.7.3-linux-x64-031aca2e.tgz]
   2018-04-02T16:08:09.07-0700 [STG/0] OUT        Using default npm version: 2.15.11
   2018-04-02T16:08:09.13-0700 [STG/0] OUT        Downloading and installing yarn (0.20.0)...
   2018-04-02T16:08:09.32-0700 [STG/0] OUT        Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/a650821a-7cdd-4c2e-a81f-3453412f30a3_484b714a19dde2c8020f535def648881bd3cc90cbba9779639687f892291b9ab/dependencies/https___buildpacks.cloudfoundry.org_dependencies_yarn_yarn-v0.20.0-12df75bd.tar.gz]
   2018-04-02T16:08:09.79-0700 [STG/0] OUT        Installed yarn 0.20.0
   2018-04-02T16:08:09.79-0700 [STG/0] OUT -----> Restoring cache
   2018-04-02T16:08:10.17-0700 [STG/0] OUT        Loading 3 from cacheDirectories (default):
   2018-04-02T16:08:10.17-0700 [STG/0] OUT        - .npm (not cached - skipping)
   2018-04-02T16:08:10.17-0700 [STG/0] OUT        - .cache/yarn
   2018-04-02T16:08:10.18-0700 [STG/0] OUT        - bower_components (not cached - skipping)
   2018-04-02T16:08:10.18-0700 [STG/0] OUT -----> Building dependencies
   2018-04-02T16:08:10.18-0700 [STG/0] OUT        Installing node modules (yarn.lock)
   2018-04-02T16:08:10.18-0700 [STG/0] OUT        Running yarn in online mode
   2018-04-02T16:08:10.18-0700 [STG/0] OUT        To run yarn in offline mode, see: https://yarnpkg.com/blog/2016/11/24/offline-mirror
   2018-04-02T16:08:10.39-0700 [STG/0] OUT        yarn install v0.20.0
   2018-04-02T16:08:10.58-0700 [STG/0] OUT        [1/4] Resolving packages...
   2018-04-02T16:08:11.26-0700 [STG/0] OUT        [2/4] Fetching packages...
   2018-04-02T16:08:12.94-0700 [STG/0] OUT        warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
   2018-04-02T16:08:12.94-0700 [STG/0] OUT        info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
   2018-04-02T16:08:12.94-0700 [STG/0] OUT        [3/4] Linking dependencies...
   2018-04-02T16:08:24.72-0700 [STG/0] OUT        [4/4] Building fresh packages...
   2018-04-02T16:08:26.91-0700 [STG/0] OUT        Done in 16.53s.
   2018-04-02T16:08:44.17-0700 [STG/0] ERR     error react-scripts@1.0.17: The engine "node" is incompatible with this module. Expected version ">=6".
   2018-04-02T16:08:44.18-0700 [STG/0] ERR error Found incompatible module
   2018-04-02T16:08:44.20-0700 [STG/0] OUT        yarn.lock is outdated
   2018-04-02T16:08:44.20-0700 [STG/0] OUT -----> Caching build
   2018-04-02T16:08:44.21-0700 [STG/0] OUT        Clearing previous node cache
   2018-04-02T16:08:44.21-0700 [STG/0] OUT        Saving 3 cacheDirectories (default):
   2018-04-02T16:08:44.21-0700 [STG/0] OUT        - .npm (nothing to cache)
   2018-04-02T16:08:44.21-0700 [STG/0] OUT        - .cache/yarn
   2018-04-02T16:08:46.24-0700 [STG/0] OUT        - bower_components (nothing to cache)
   2018-04-02T16:08:47.32-0700 [STG/0] OUT -----> Build succeeded!
   2018-04-02T16:08:58.10-0700 [STG/190] OUT -----> Uploading droplet (67M)
   2018-04-02T16:09:12.82-0700 [DEA/190] OUT Starting app instance (index 0) with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740
   2018-04-02T16:09:21.91-0700 [App/0] ERR     module.js:327
   2018-04-02T16:09:21.91-0700 [App/0] ERR     throw err;
   2018-04-02T16:09:21.91-0700 [App/0] ERR     ^
   2018-04-02T16:09:21.91-0700 [App/0] ERR Error: Cannot find module '/home/vcap/app/server/app.js'
   2018-04-02T16:09:21.91-0700 [App/0] ERR     at Function.Module._resolveFilename (module.js:325:15)
   2018-04-02T16:09:21.91-0700 [App/0] ERR     at Function.Module._load (module.js:276:25)
   2018-04-02T16:09:21.91-0700 [App/0] ERR     at Function.Module.runMain (module.js:441:10)
   2018-04-02T16:09:21.91-0700 [App/0] ERR     at startup (node.js:139:18)
   2018-04-02T16:09:21.91-0700 [App/0] ERR     at node.js:990:3
   2018-04-02T16:09:21.91-0700 [App/0] OUT
   2018-04-02T16:09:21.93-0700 [DEA/190] ERR Instance (index 0) failed to start accepting connections
   2018-04-02T16:09:21.94-0700 [API/10] OUT App instance exited with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 payload: {"cc_partition"=>"default", "droplet"=>"7455ebd8-c0b0-4768-b9d6-c7083ab6a740", "version"=>"b461b656-25ab-4959-ae67-6cf204839279", "instance"=>"c26be09c8c6e478490811f8a864f5087", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1522710561}
   2018-04-02T16:09:21.94-0700 [API/3] OUT App instance exited with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 payload: {"cc_partition"=>"default", "droplet"=>"7455ebd8-c0b0-4768-b9d6-c7083ab6a740", "version"=>"b461b656-25ab-4959-ae67-6cf204839279", "instance"=>"c26be09c8c6e478490811f8a864f5087", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1522710561}

Any help would be appreciated!

**Comment by abhishekdhaduvai** [comment]
Hi @mgit7 

This sample app uses react-scripts, which requires node version 6 or later. By default CloudFoundry uses an older version of node, and that is why you're seeing that error when you try to push to the cloud. You can tell CloudFoundry to use specific node versions in your package.json file. Add the following line to your package.json. 

`"engines" : { "node" : ">=6" }`

or

`"engines": {"node": "6.9.5"}` for a specific version. 

I've created a seed application using React, with a Node server and UAA if you want to check it out. Here's the link - https://github.com/abhishekdhaduvai/seed-applications/tree/react

**Comment by mgit7** [comment]
I ended up changing the package.json file to what you recommended. That error doesnt show up anymore but the app is still not able to run the instance on the cloud. It continues trying until timing out. I am doing this all on Windows 10. I am able to successfully push an app to the cloud, but I cant seem to do it with a React app.

**Comment by abhishekdhaduvai** [comment]
I was able to deploy this application to the cloud.
https://react-sample-dev.run.aws-usw02-pr.ice.predix.io/#/dashboard

Check your application's logs to identify the problem. You can get the logs by running ```cf logs your-app-name --recent```.

Here's some issues you might be having

1. Since this app was bootstrapped using create-react-app, it's distribution version does not include the package.json file, but nodejs_buildpack is expecting a package.json file to install the dependencies. One way to get around this is, after you run ```npm run build```, copy the package.json file from your root directory to the build directory.

2. Not enough memory. Make sure assign enough memory in the manifest file. You can scale your app up or down after you deploy. 

Here's my manifest file for reference

```---
applications:
  - name: react-sample-dev
    memory: 512M
    buildpack: nodejs_buildpack
    command: serve
    path: build
env:
    node_env: production
```

Don't forget to add serve to your package.json before you copy. You can add it by running ```npm i serve --save```.

**Comment by mgit7** [comment]
Okay so one thing I was forgetting was to `npm run build` but when I run it its throwing this error. This is for the other app but same concept.

Error:

> predix-react-app@ scss C:\Users\User\predixwork\px-sample-app-react-directions-master\px-sample-app-react-directions-master
>  ./scripts/build-scss
> 
> '.' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! predix-react-app@ scss: `./scripts/build-scss`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the predix-react-app@ scss script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-04-03T21_28_50_257Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! predix-react-app@ build: `react-scripts build && npm run-script scss`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the predix-react-app@ build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-04-03T21_28_50_293Z-debug.log`
> 

Package.json

> {
>   "name": "predix-react-app",
>   "private": true,
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build && npm run-script scss",
>     "test": "react-scripts test --env=jsdom",
>     "eject": "react-scripts eject",
>     "scss": "./scripts/build-scss"
>   },
>   "dependencies": {
>     "@mapbox/geo-viewport": "^0.2.2",
>     "lodash.debounce": "^4.0.8",
>     "react": "^16.2.0",
>     "react-dom": "^16.2.0",
>     "react-router-dom": "^4.2.2",
>     "react-scripts": "1.0.17"
>   },
>   "engines": {
>     "node": ">=6"
>   },
>   "devDependencies": {
>     "autoprefixer": "^7.2.4",
>     "cssnano": "^3.10.0",
>     "node-sass": "^4.7.2",
>     "node-sass-import-once": "^1.2.0",
>     "postcss": "^6.0.16"
>   },
>   "license": "BSD-3-Clause"
> }


I looked into the package.json documentation and it seems like everything is set up correctly. Here is what I have.

**Comment by abhishekdhaduvai** [comment]
Are you running this in the command prompt? It doesn't support the script by default. To run it in the command prompt, make the following change in your package.json scripts.

```"scss": "./scripts/build-scss"``` to ```"scss": "node scripts/build-scss"```

Or, you can run it without making the changes in a UNIX shell like Git Bash.

**Comment by mgit7** [comment]
Thank you very much! I was able to solve the issue. I wasnt pointing the path to the right directory.

**Comment by mgit7** [comment]
Im sorry, I wasnt able to resolve this issue when deploying. This is what I am getting now:

` 2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/serve/bin/serve.js:83
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR detect(port).then(async open => {
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR                   ^^^^^
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR SyntaxError: missing ) after argument list
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR     at Object.exports.runInThisContext (vm.js:73:16)
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:543:28)
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:580:10)
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR     at Module.load (module.js:488:32)
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:447:12)
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:439:3)
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR     at Module.runMain (module.js:605:10)
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR     at run (bootstrap_node.js:418:7)
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR     at startup (bootstrap_node.js:139:9)
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] ERR     at bootstrap_node.js:533:3
   2018-04-20T14:44:10.31-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2018-04-20T14:44:10.35-0700 [CELL/0] OUT Destroying container
   2018-04-20T14:44:10.37-0700 [API/8] OUT Process has crashed with type: "web"
   2018-04-20T14:44:10.38-0700 [API/8] OUT App instance exited with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 1 error(s) occurred:\n\n* Exited with status 1\n* cancelled", "crash_count"=>1, "crash_timestamp"=>1524260650337761054, "version"=>"9c41bfa8-c1b2-4c29-bad4-d6c8faa3ae01"}
   2018-04-20T14:44:10.44-0700 [CELL/0] OUT Creating container
   2018-04-20T14:44:12.47-0700 [CELL/0] OUT Successfully created container
   2018-04-20T14:44:18.76-0700 [CELL/0] OUT Starting health monitoring of container
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/serve/bin/serve.js:83
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR detect(port).then(async open => {
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR                   ^^^^^
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR SyntaxError: missing ) after argument list
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR     at Object.exports.runInThisContext (vm.js:73:16)
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:543:28)
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:580:10)
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR     at Module.load (module.js:488:32)
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:447:12)
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:439:3)
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR     at Module.runMain (module.js:605:10)
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR     at run (bootstrap_node.js:418:7)
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR     at startup (bootstrap_node.js:139:9)
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] ERR     at bootstrap_node.js:533:3
   2018-04-20T14:44:18.92-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2018-04-20T14:44:18.97-0700 [CELL/0] OUT Destroying container
   2018-04-20T14:44:18.99-0700 [API/8] OUT Process has crashed with type: "web"
   2018-04-20T14:44:19.02-0700 [API/8] OUT App instance exited with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 1 error(s) occurred:\n\n* Exited with status 1\n* cancelled", "crash_count"=>2, "crash_timestamp"=>1524260658957927006, "version"=>"9c41bfa8-c1b2-4c29-bad4-d6c8faa3ae01"}
   2018-04-20T14:44:19.04-0700 [CELL/0] OUT Creating container
   2018-04-20T14:44:19.56-0700 [CELL/0] OUT Successfully created container
   2018-04-20T14:44:21.50-0700 [CELL/0] OUT Successfully destroyed container
   2018-04-20T14:44:25.82-0700 [CELL/0] OUT Starting health monitoring of container
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/serve/bin/serve.js:83
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR detect(port).then(async open => {
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR                   ^^^^^
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR SyntaxError: missing ) after argument list
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR     at Object.exports.runInThisContext (vm.js:73:16)
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:543:28)
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:580:10)
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR     at Module.load (module.js:488:32)
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:447:12)
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:439:3)
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR     at Module.runMain (module.js:605:10)
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR     at run (bootstrap_node.js:418:7)
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR     at startup (bootstrap_node.js:139:9)
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] ERR     at bootstrap_node.js:533:3
   2018-04-20T14:44:25.98-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2018-04-20T14:44:26.01-0700 [CELL/0] OUT Destroying container
   2018-04-20T14:44:26.06-0700 [API/1] OUT Process has crashed with type: "web"
   2018-04-20T14:44:26.08-0700 [API/1] OUT App instance exited with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 1 error(s) occurred:\n\n* Exited with status 1\n* cancelled", "crash_count"=>3, "crash_timestamp"=>1524260666041229992, "version"=>"9c41bfa8-c1b2-4c29-bad4-d6c8faa3ae01"}
   2018-04-20T14:44:28.51-0700 [CELL/0] OUT Successfully destroyed container
   2018-04-20T14:45:15.18-0700 [CELL/0] OUT Creating container
   2018-04-20T14:45:15.84-0700 [CELL/0] OUT Successfully created container
   2018-04-20T14:45:23.42-0700 [CELL/0] OUT Starting health monitoring of container
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/serve/bin/serve.js:83
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR detect(port).then(async open => {
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR                   ^^^^^
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR SyntaxError: missing ) after argument list
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR     at Object.exports.runInThisContext (vm.js:73:16)
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:543:28)
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:580:10)
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR     at Module.load (module.js:488:32)
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:447:12)
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:439:3)
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR     at Module.runMain (module.js:605:10)
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR     at run (bootstrap_node.js:418:7)
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR     at startup (bootstrap_node.js:139:9)
   2018-04-20T14:45:23.58-0700 [APP/PROC/WEB/0] ERR     at bootstrap_node.js:533:3
   2018-04-20T14:45:23.59-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2018-04-20T14:45:23.63-0700 [CELL/0] OUT Destroying container
   2018-04-20T14:45:23.66-0700 [API/4] OUT Process has crashed with type: "web"
   2018-04-20T14:45:23.68-0700 [API/4] OUT App instance exited with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 1 error(s) occurred:\n\n* Exited with status 1\n* cancelled", "crash_count"=>4, "crash_timestamp"=>1524260723643104196, "version"=>"9c41bfa8-c1b2-4c29-bad4-d6c8faa3ae01"}
   2018-04-20T14:45:26.55-0700 [CELL/0] OUT Successfully destroyed container
   2018-04-20T14:46:45.89-0700 [CELL/0] OUT Creating container
   2018-04-20T14:46:46.38-0700 [CELL/0] OUT Successfully created container
   2018-04-20T14:46:52.79-0700 [CELL/0] OUT Starting health monitoring of container
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/serve/bin/serve.js:83
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR detect(port).then(async open => {
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR                   ^^^^^
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR SyntaxError: missing ) after argument list
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR     at Object.exports.runInThisContext (vm.js:73:16)
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:543:28)
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:580:10)
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR     at Module.load (module.js:488:32)
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:447:12)
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:439:3)
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR     at Module.runMain (module.js:605:10)
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR     at run (bootstrap_node.js:418:7)
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR     at startup (bootstrap_node.js:139:9)
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] ERR     at bootstrap_node.js:533:3
   2018-04-20T14:46:52.93-0700 [APP/PROC/WEB/0] OUT Exit status 1
   2018-04-20T14:46:52.96-0700 [CELL/0] OUT Destroying container
   2018-04-20T14:46:52.97-0700 [API/1] OUT Process has crashed with type: "web"
   2018-04-20T14:46:52.99-0700 [API/1] OUT App instance exited with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 1 error(s) occurred:\n\n* Exited with status 1\n* cancelled", "crash_count"=>5, "crash_timestamp"=>1524260812944598157, "version"=>"9c41bfa8-c1b2-4c29-bad4-d6c8faa3ae01"}
   2018-04-20T14:46:55.45-0700 [CELL/0] OUT Successfully destroyed container`

**Comment by abhishekdhaduvai** [comment]
Hi @mgit7 

It's a known error. You can check the updates on the issue here: https://github.com/zeit/serve/issues/348

Apparently, async await is supported by Node versions 7.6 and above. We could add an engine version in our package.json file like "engines": ```{"node": ">=7.6.0"}```, but unfortunately cloud foundry only has up to Node version 7.5.0 (at the time of writing this). 

One solution suggested in the discussion on the issue was to downgrade 'serve' to version 6.5.3. I've tested this and it worked for me.

Here's my package.json that I put in my build dir for reference:
```
{
  "name": "px-sample-app-react",
  "version": "0.0.1-alpha.1",
  "engines": {
    "node": ">=6.9.0"
  },
  "dependencies": {
    "serve": "6.5.3"
  },
  "license": "BSD-3-Clause"
}
```

Notice that I have only 'serve' as my dependency. You don't need your other dependencies in this file because ```npm run build``` bundles all other dependencies in one .js file.

**Comment by MichaelZaporozhets** [comment]
> Thank you very much! I was able to solve the issue. I wasnt pointing the path to the right directory.

closing issue per resolution here.
